# Configure the supervisord service

- name: Create a shell script that keeps the call for the runner
  copy:
    src: "{{ role_path }}/files/gitlab-runner.sh"
    dest: /home/$USER/bin/gitlab-runner.sh


- name: Make it executable
  file:
    path: /home/$USER/bin/gitlab-runner.sh
    mode: u+x


- name: Create supervisord ini
  copy:
    src: "{{ role_path }}/files/gitlab-runner.ini"
    dest: /home/$USER/etc/services.d/gitlab-runner.ini


- name: Tell supervisord to refresh its configuration
  supervisorctl:
    name: gitlab-runner
    state: present


- name: Tell supervisord to start the service
  supervisorctl:
    name: gitlab-runner
    state: started


- name: Optional check supervisorctl status
  shell: |
   supervisorctl status
  register: supervisorctlstatus


- name: If it is not in state RUNNING, check your configuration
  debug:
    var: supervisorctlstatus.stdout_lines
